[CMSP-79] Release 1.3.2 (#233)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,7 +5,8 @@ workflows:
     jobs:
       - lint
       - test-behat
-      - test-phpunit
+      - test-phpunit-74
+      - test-phpunit-82
   nightly:
     triggers:
       - schedule:
@@ -20,7 +21,7 @@ jobs:
   lint:
     working_directory: ~/pantheon-systems/wp-native-php-sessions
     docker:
-      - image: quay.io/pantheon-public/build-tools-ci:6.x
+      - image: quay.io/pantheon-public/build-tools-ci:8.x-php8.2
     steps:
       - checkout
       - restore_cache:
@@ -39,48 +40,48 @@ jobs:
     working_directory: ~/pantheon-systems/wp-native-php-sessions
     parallelism: 1
     docker:
-    - image: quay.io/pantheon-public/build-tools-ci:6.x
+      - image: quay.io/pantheon-public/build-tools-ci:8.x-php8.2
     steps:
-    - checkout
-    - restore_cache:
-        keys:
-          - test-behat-dependencies-{{ checksum "composer.json" }}
-    - run: composer install -n --prefer-dist
-    - save_cache:
-        key: test-behat-dependencies-{{ checksum "composer.json" }}
-        paths:
-          - vendor
-    - run: echo $(openssl rand -hex 8) > /tmp/WORDPRESS_ADMIN_PASSWORD
-    - run: |
-        echo 'export TERMINUS_ENV=ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
-        echo 'export TERMINUS_SITE=wp-native-php-sessions' >> $BASH_ENV
-        echo 'export SITE_ENV=wp-native-php-sessions.ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
-        echo 'export WORDPRESS_ADMIN_USERNAME=pantheon' >> $BASH_ENV
-        echo 'export WORDPRESS_ADMIN_EMAIL=no-reply@getpantheon.com' >> $BASH_ENV
-        echo 'export WORDPRESS_ADMIN_PASSWORD=$(cat /tmp/WORDPRESS_ADMIN_PASSWORD)' >> $BASH_ENV
-        source $BASH_ENV
-    - run: echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
-    - run: |
-        if [ -z "$GITHUB_TOKEN" ]; then
-          echo "GITHUB_TOKEN environment variables missing; assuming unauthenticated build"
-          exit 0
-        fi
-        echo "Setting GitHub OAuth token with suppressed ouput"
-        {
-          composer config -g github-oauth.github.com $GITHUB_TOKEN
-        } &> /dev/null
-    - run: |
-        if [ -z "$TERMINUS_TOKEN" ]; then
-          echo "TERMINUS_TOKEN environment variables missing; assuming unauthenticated build"
-          exit 0
-        fi
-        terminus auth:login --machine-token=$TERMINUS_TOKEN
-    - run: ./bin/behat-prepare.sh
-    - run: ./bin/behat-test.sh --strict
-    - run:
-        command: ./bin/behat-cleanup.sh
-        when: always
-  test-phpunit:
+      - checkout
+      - restore_cache:
+          keys:
+            - test-behat-dependencies-{{ checksum "composer.json" }}
+      - run: composer install -n --prefer-dist
+      - save_cache:
+          key: test-behat-dependencies-{{ checksum "composer.json" }}
+          paths:
+            - vendor
+      - run: echo $(openssl rand -hex 8) > /tmp/WORDPRESS_ADMIN_PASSWORD
+      - run: |
+          echo 'export TERMINUS_ENV=ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
+          echo 'export TERMINUS_SITE=wp-native-php-sessions' >> $BASH_ENV
+          echo 'export SITE_ENV=wp-native-php-sessions.ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
+          echo 'export WORDPRESS_ADMIN_USERNAME=pantheon' >> $BASH_ENV
+          echo 'export WORDPRESS_ADMIN_EMAIL=no-reply@getpantheon.com' >> $BASH_ENV
+          echo 'export WORDPRESS_ADMIN_PASSWORD=$(cat /tmp/WORDPRESS_ADMIN_PASSWORD)' >> $BASH_ENV
+          source $BASH_ENV
+      - run: echo "StrictHostKeyChecking no" >> "$HOME/.ssh/config"
+      - run: |
+          if [ -z "$GITHUB_TOKEN" ]; then
+            echo "GITHUB_TOKEN environment variables missing; assuming unauthenticated build"
+            exit 0
+          fi
+          echo "Setting GitHub OAuth token with suppressed ouput"
+          {
+            composer config -g github-oauth.github.com $GITHUB_TOKEN
+          } &> /dev/null
+      - run: |
+          if [ -z "$TERMINUS_TOKEN" ]; then
+            echo "TERMINUS_TOKEN environment variables missing; assuming unauthenticated build"
+            exit 0
+          fi
+          terminus auth:login --machine-token=$TERMINUS_TOKEN
+      - run: ./bin/behat-prepare.sh
+      - run: ./bin/behat-test.sh --strict
+      - run:
+          command: ./bin/behat-cleanup.sh
+          when: always
+  test-phpunit-74:
     working_directory: ~/pantheon-systems/wp-native-php-sessions
     docker:
       - image: circleci/php:7.4-node-browsers
@@ -92,10 +93,10 @@ jobs:
       - checkout
       - restore_cache:
           keys:
-            - test-phpunit-dependencies-{{ checksum "composer.json" }}
+            - test-phpunit-74-dependencies-{{ checksum "composer.json" }}
       - run: composer install -n --prefer-dist
       - save_cache:
-          key: test-phpunit-dependencies-{{ checksum "composer.json" }}
+          key: test-phpunit-74-dependencies-{{ checksum "composer.json" }}
           paths:
             - vendor
       - run:
@@ -109,6 +110,44 @@ jobs:
             sudo docker-php-ext-enable imagick
             sudo docker-php-ext-install mysqli
             sudo apt-get install mariadb-client-10.5
+      - run:
+          name: "Run Tests"
+          command: |
+            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
+            composer phpunit
+            WP_MULTISITE=1 composer phpunit
+            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
+            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 nightly true
+            composer phpunit
+  test-phpunit-82:
+    working_directory: ~/pantheon-systems/wp-native-php-sessions
+    docker:
+      - image: cimg/php:8.2.0
+      - image: circleci/mariadb:10.3
+    environment:
+      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
+      - WP_CORE_DIR: "/tmp/wordpress/"
+    steps:
+      - checkout
+      - restore_cache:
+          keys:
+            - test-phpunit-82-dependencies-{{ checksum "composer.json" }}
+      - run: composer install -n --prefer-dist
+      - save_cache:
+          key: test-phpunit-82-dependencies-{{ checksum "composer.json" }}
+          paths:
+            - vendor
+      - run:
+          name: "Install Extras"
+          command: |
+            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
+            sudo apt-get update
+            sudo apt-get install subversion
+            sudo apt-get install -y libmagickwand-dev --no-install-recommends
+            yes '' | sudo pecl install imagick || true
+            sudo docker-php-ext-enable imagick
+            sudo docker-php-ext-install mysqli
+            sudo apt-get install mariadb-client-10.6
       - run:
           name: "Run Tests"
           command: |
